### ISSUE TITLE
Before I start 

### ISSUE THREAD

**Issue by zanco** [F4HVO/m10-aprs#1]
Hi,
thanks for your software. I plan to try to program it into an M10 "hanging around" over here.

I am missing one thing, what is the setting for the transmitter frequency ?

Thanks,
PE2BZ

**Comment by F4HVO** [comment]
Hi ! Sorry for the delay, the message notification got lost in my mail box.
The formula is the following (see RadioAdf7012.cpp). 
First compute f_pfd (f_crystal is 8MHz). Then use it to compute the final frequency (f_tx)
```
    // Formula : f_pfd = f_crystal / r_divider
    // f_tx = f_pfd * ( integer_n + fractional_n / 4086 )
```

Example for 438.510MHz:
```
    adf_config.r0.r_divider = 4 ;
    adf_config.r1.integer_n = 219 ;
    adf_config.r1.fractional_n = 1050 ;
```
